spring:
  application:
    name: spring-boot-core-backend
  api:
    version: 1.0.0

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  security:
    oauth2:
      client:
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
              - openid
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            client-name: Google
            authorization-grant-type: authorization_code
            client-authentication-method: basic
            provider: google

jwt:
  signer-key: v5IjSYvsOmQ7n7lpgUmaVXHmaE57wagF6aPJicyY17UPW7IwyYisMX5HIc2VIgeGz78NrRbhzdohcO2A7ckPug

cloud:
  cloudinary:
    cloud-name: ${CLOUDINARY_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}

logging:
  level:
    org.springframework.security: DEBUG
